name: Publish to TestPyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Adjust as needed

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl jq wget tar python3 python3-pip

      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          echo "export PATH=\"$HOME/miniconda/bin:$PATH\"" >> $GITHUB_ENV

      - name: Create Conda environment
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda create -y -n ${{ env.ENV_NAME }} python=${{ env.PYTHON_VERSION }}
          conda activate ${{ env.ENV_NAME }}

      - name: Build distributions
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          id-token: write  # This permission is mandatory for trusted publishing

      - name: Verify upload
        run: |
          pip install --upgrade pip
          pip install twine
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*

